language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install python-lxml
install: 
  - pip install flake8
  # the following are installed because its needed for postgres tests to run
  - pip install psycopg2
  - pip install mock
  - pip install pycountry
  - pip install coveralls
  - python setup.py install
  - pip install git+git://github.com/openlabs/nereid-test@develop
script:
  - coverage run setup.py test
  - python setup.py test_on_postgres
  - flake8 .
after_success:
  coveralls
